// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupId.def.proto

#ifndef PROTOBUF_GroupId_2edef_2eproto__INCLUDED
#define PROTOBUF_GroupId_2edef_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tt_im_group {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GroupId_2edef_2eproto();
void protobuf_AssignDesc_GroupId_2edef_2eproto();
void protobuf_ShutdownFile_GroupId_2edef_2eproto();

class GroupId;

enum GroupType {
  GENERIC_GROUP_TYPE = 0,
  COMPERE_GROUP_TYPE = 1,
  FOUCS_GROUP_TYPE = 2,
  FREE_GROUP_TYPE = 2147483647
};
bool GroupType_IsValid(int value);
const GroupType GroupType_MIN = GENERIC_GROUP_TYPE;
const GroupType GroupType_MAX = FREE_GROUP_TYPE;
const ::google::protobuf::EnumDescriptor* GroupType_descriptor();
inline const ::std::string& GroupType_Name(GroupType value) {
  return ::google::protobuf::internal::NameOfEnum(
    GroupType_descriptor(), value);
}
inline bool GroupType_Parse(
    const ::std::string& name, GroupType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GroupType>(
    GroupType_descriptor(), name, value);
}
// ===================================================================

class GroupId : public ::google::protobuf::Message {
 public:
  GroupId();
  virtual ~GroupId();

  GroupId(const GroupId& from);

  inline GroupId& operator=(const GroupId& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GroupId& default_instance();

  void Swap(GroupId* other);

  // implements Message ----------------------------------------------

  GroupId* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GroupId& from);
  void MergeFrom(const GroupId& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 number = 1;
  inline bool has_number() const;
  inline void clear_number();
  static const int kNumberFieldNumber = 1;
  inline ::google::protobuf::uint64 number() const;
  inline void set_number(::google::protobuf::uint64 value);

  // required .tt_im_group.GroupType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::tt_im_group::GroupType type() const;
  inline void set_type(::tt_im_group::GroupType value);

  // @@protoc_insertion_point(class_scope:tt_im_group.GroupId)
 private:
  inline void set_has_number();
  inline void clear_has_number();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 number_;
  int type_;
  friend void  protobuf_AddDesc_GroupId_2edef_2eproto();
  friend void protobuf_AssignDesc_GroupId_2edef_2eproto();
  friend void protobuf_ShutdownFile_GroupId_2edef_2eproto();

  void InitAsDefaultInstance();
  static GroupId* default_instance_;
};
// ===================================================================


// ===================================================================

// GroupId

// required uint64 number = 1;
inline bool GroupId::has_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GroupId::set_has_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GroupId::clear_has_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GroupId::clear_number() {
  number_ = GOOGLE_ULONGLONG(0);
  clear_has_number();
}
inline ::google::protobuf::uint64 GroupId::number() const {
  // @@protoc_insertion_point(field_get:tt_im_group.GroupId.number)
  return number_;
}
inline void GroupId::set_number(::google::protobuf::uint64 value) {
  set_has_number();
  number_ = value;
  // @@protoc_insertion_point(field_set:tt_im_group.GroupId.number)
}

// required .tt_im_group.GroupType type = 2;
inline bool GroupId::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GroupId::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GroupId::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GroupId::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::tt_im_group::GroupType GroupId::type() const {
  // @@protoc_insertion_point(field_get:tt_im_group.GroupId.type)
  return static_cast< ::tt_im_group::GroupType >(type_);
}
inline void GroupId::set_type(::tt_im_group::GroupType value) {
  assert(::tt_im_group::GroupType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:tt_im_group.GroupId.type)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tt_im_group

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::tt_im_group::GroupType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tt_im_group::GroupType>() {
  return ::tt_im_group::GroupType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GroupId_2edef_2eproto__INCLUDED
