// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupId.def.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GroupId.def.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tt_im_group {

namespace {

const ::google::protobuf::Descriptor* GroupId_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GroupId_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* GroupType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GroupId_2edef_2eproto() {
  protobuf_AddDesc_GroupId_2edef_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GroupId.def.proto");
  GOOGLE_CHECK(file != NULL);
  GroupId_descriptor_ = file->message_type(0);
  static const int GroupId_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupId, number_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupId, type_),
  };
  GroupId_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GroupId_descriptor_,
      GroupId::default_instance_,
      GroupId_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupId, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupId, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GroupId));
  GroupType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GroupId_2edef_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GroupId_descriptor_, &GroupId::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GroupId_2edef_2eproto() {
  delete GroupId::default_instance_;
  delete GroupId_reflection_;
}

void protobuf_AddDesc_GroupId_2edef_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021GroupId.def.proto\022\013tt_im_group\"\?\n\007Grou"
    "pId\022\016\n\006number\030\001 \002(\004\022$\n\004type\030\002 \002(\0162\026.tt_i"
    "m_group.GroupType*j\n\tGroupType\022\026\n\022GENERI"
    "C_GROUP_TYPE\020\000\022\026\n\022COMPERE_GROUP_TYPE\020\001\022\024"
    "\n\020FOUCS_GROUP_TYPE\020\002\022\027\n\017FREE_GROUP_TYPE\020"
    "\377\377\377\377\007", 205);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GroupId.def.proto", &protobuf_RegisterTypes);
  GroupId::default_instance_ = new GroupId();
  GroupId::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GroupId_2edef_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GroupId_2edef_2eproto {
  StaticDescriptorInitializer_GroupId_2edef_2eproto() {
    protobuf_AddDesc_GroupId_2edef_2eproto();
  }
} static_descriptor_initializer_GroupId_2edef_2eproto_;
const ::google::protobuf::EnumDescriptor* GroupType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupType_descriptor_;
}
bool GroupType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 2147483647:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int GroupId::kNumberFieldNumber;
const int GroupId::kTypeFieldNumber;
#endif  // !_MSC_VER

GroupId::GroupId()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tt_im_group.GroupId)
}

void GroupId::InitAsDefaultInstance() {
}

GroupId::GroupId(const GroupId& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tt_im_group.GroupId)
}

void GroupId::SharedCtor() {
  _cached_size_ = 0;
  number_ = GOOGLE_ULONGLONG(0);
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GroupId::~GroupId() {
  // @@protoc_insertion_point(destructor:tt_im_group.GroupId)
  SharedDtor();
}

void GroupId::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GroupId::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroupId::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupId_descriptor_;
}

const GroupId& GroupId::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GroupId_2edef_2eproto();
  return *default_instance_;
}

GroupId* GroupId::default_instance_ = NULL;

GroupId* GroupId::New() const {
  return new GroupId;
}

void GroupId::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<GroupId*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(number_, type_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GroupId::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tt_im_group.GroupId)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 number = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &number_)));
          set_has_number();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_type;
        break;
      }

      // required .tt_im_group.GroupType type = 2;
      case 2: {
        if (tag == 16) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::tt_im_group::GroupType_IsValid(value)) {
            set_type(static_cast< ::tt_im_group::GroupType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tt_im_group.GroupId)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tt_im_group.GroupId)
  return false;
#undef DO_
}

void GroupId::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tt_im_group.GroupId)
  // required uint64 number = 1;
  if (has_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->number(), output);
  }

  // required .tt_im_group.GroupType type = 2;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tt_im_group.GroupId)
}

::google::protobuf::uint8* GroupId::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tt_im_group.GroupId)
  // required uint64 number = 1;
  if (has_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->number(), target);
  }

  // required .tt_im_group.GroupType type = 2;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tt_im_group.GroupId)
  return target;
}

int GroupId::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 number = 1;
    if (has_number()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->number());
    }

    // required .tt_im_group.GroupType type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GroupId::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GroupId* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GroupId*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GroupId::MergeFrom(const GroupId& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_number()) {
      set_number(from.number());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GroupId::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GroupId::CopyFrom(const GroupId& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupId::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void GroupId::Swap(GroupId* other) {
  if (other != this) {
    std::swap(number_, other->number_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GroupId::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GroupId_descriptor_;
  metadata.reflection = GroupId_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tt_im_group

// @@protoc_insertion_point(global_scope)
